version: '3.8'

services:
  unisentinal:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - UNIFI_HOST=192.168.0.1
    volumes:
      # Mount a volume for all persistent data (database, settings, logs)
      - ./config:/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s